export const SUCCESS = "SUCCESS";
export const FAILURE = "FAILURE";
export const REQUESTING = "REQUESTING";

export const FETCH_STATE_REQUEST = "FETCH_STATE_REQUEST";
export const FETCH_STATE_SUCCESS = "FETCH_STATE_SUCCESS";
export const FETCH_STATE_FAILURE = "FETCH_STATE_FAILURE";

export const FETCH_COUNTRY_CODE_REQUEST = "FETCH_COUNTRY_CODE_REQUEST";
export const FETCH_COUNTRY_CODE_SUCCESS = "FETCH_COUNTRY_CODE_SUCCESS";
export const FETCH_COUNTRY_CODE_FAILURE = "FETCH_COUNTRY_CODE_FAILURE";

export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";

export const FETCH_TEMP_REQUEST = "FETCH_TEMP_REQUEST";
export const FETCH_TEMP_SUCCESS = "FETCH_TEMP_SUCCESS";
export const FETCH_TEMP_FAILURE = "FETCH_TEMP_FAILURE";

export const FETCH_WIND_REQUEST = "FETCH_WIND_REQUEST";
export const FETCH_WIND_SUCCESS = "FETCH_WIND_SUCCESS";
export const FETCH_WIND_FAILURE = "FETCH_WIND_FAILURE";

export const FETCH_NEXT_MONTH_REQUEST = "FETCH_NEXT_MONTH_REQUEST";
export const FETCH_NEXT_MONTH_SUCCESS = "FETCH_NEXT_MONTH_SUCCESS";
export const FETCH_NEXT_MONTH_FAILURE = "FETCH_NEXT_MONTH_FAILURE";

export const FETCH_CURRENT_MONTH_REQUEST = "FETCH_CURRENT_MONTH_REQUEST";
export const FETCH_CURRENT_MONTH_SUCCESS = "FETCH_CURRENT_MONTH_SUCCESS";
export const FETCH_CURRENT_MONTH_FAILURE = "FETCH_CURRENT_MONTH_FAILURE";

export const FETCH_LAST_MONTH_REQUEST = "FETCH_LAST_MONTH_REQUEST";
export const FETCH_LAST_MONTH_SUCCESS = "FETCH_LAST_MONTH_SUCCESS";
export const FETCH_LAST_MONTH_FAILURE = "FETCH_LAST_MONTH_FAILURE";

export const SAVE_PINCODE_REQUEST = "SAVE_PINCODE_REQUEST";
export const SAVE_PINCODE_SUCCESS = "SAVE_PINCODE_SUCCESS";
export const SAVE_PINCODE_FAILURE = "SAVE_PINCODE_FAILURE";
